package net.pl3x.forge.entity.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;
import net.pl3x.forge.entity.EntityVehicle;

public class ModelGoCart extends ModelBase {
    private ModelRenderer container;
    private ModelRenderer body_container;
    private ModelRenderer wheel_fl;
    private ModelRenderer wheel_fr;
    private ModelRenderer wheel_rl;
    private ModelRenderer wheel_rr;
    private ModelRenderer seat_container;

    public ModelGoCart() {
        textureWidth = 64;
        textureHeight = 32;
        ModelRenderer rubber_right_rl = new ModelRenderer(this, 2, 0);
        rubber_right_rl.addBox(3.0F, -3.0F, 0.0F, 4, 6, 5, 0.0F);
        body_container = new ModelRenderer(this, 0, 0);
        body_container.setRotationPoint(0.0F, -8.0F, 0.0F);
        body_container.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0, 0.0F);
        ModelRenderer rubber_outer_br2_rr = new ModelRenderer(this, 5, 4);
        rubber_outer_br2_rr.addBox(5.0F, 3.0F, 0.0F, 1, 2, 5, 0.0F);
        ModelRenderer seat_bottom_5 = new ModelRenderer(this, 1, 5);
        seat_bottom_5.addBox(0.0F, 0.0F, 5.0F, 5, 1, 5, 0.0F);
        ModelRenderer hub_bottom_fl = new ModelRenderer(this, 22, 7);
        hub_bottom_fl.addBox(-1.0F, 2.0F, 2.5F, 2, 1, 2, 0.0F);
        ModelRenderer hub_bl_fr = new ModelRenderer(this, 22, 7);
        hub_bl_fr.addBox(-2.0F, 1.0F, 2.5F, 1, 1, 2, 0.0F);
        ModelRenderer seat_bottom_1 = new ModelRenderer(this, 1, 5);
        seat_bottom_1.addBox(0.0F, 0.0F, 0.0F, 5, 1, 5, 0.0F);
        ModelRenderer rubber_outer_br2_fl = new ModelRenderer(this, 5, 4);
        rubber_outer_br2_fl.addBox(5.0F, 3.0F, 0.0F, 1, 2, 5, 0.0F);
        ModelRenderer rubber_outer_tl1_fr = new ModelRenderer(this, 4, 3);
        rubber_outer_tl1_fr.addBox(-5.0F, -6.0F, 0.0F, 2, 3, 5, 0.0F);
        ModelRenderer rubber_inner_bl_fl = new ModelRenderer(this, 5, 5);
        rubber_inner_bl_fl.addBox(-3.0F, 2.0F, 0.0F, 1, 1, 5, 0.0F);
        ModelRenderer body_4 = new ModelRenderer(this, 0, 17);
        body_4.addBox(-16.0F, 0.0F, 0.0F, 16, 2, 13, 0.0F);
        ModelRenderer rubber_inner_tr_fl = new ModelRenderer(this, 5, 5);
        rubber_inner_tr_fl.addBox(2.0F, -3.0F, 0.0F, 1, 1, 5, 0.0F);
        ModelRenderer seat_bottom_4 = new ModelRenderer(this, 1, 5);
        seat_bottom_4.addBox(-5.0F, 0.0F, -5.0F, 5, 1, 5, 0.0F);
        ModelRenderer hub_tr_rr = new ModelRenderer(this, 22, 7);
        hub_tr_rr.addBox(1.0F, -2.0F, 0.5F, 1, 1, 2, 0.0F);
        ModelRenderer body_2 = new ModelRenderer(this, 0, 17);
        body_2.addBox(-32.0F, 0.0F, 0.0F, 16, 2, 13, 0.0F);
        ModelRenderer seat_bottom_11 = new ModelRenderer(this, 1, 5);
        seat_bottom_11.addBox(-10.0F, 0.0F, -5.0F, 5, 1, 5, 0.0F);
        ModelRenderer rubber_outer_bl2_fr = new ModelRenderer(this, 5, 4);
        rubber_outer_bl2_fr.addBox(-6.0F, 3.0F, 0.0F, 1, 2, 5, 0.0F);
        ModelRenderer rubber_top_fl = new ModelRenderer(this, 0, 2);
        rubber_top_fl.addBox(-3.0F, -7.0F, 0.0F, 6, 4, 5, 0.0F);
        ModelRenderer rubber_right_fl = new ModelRenderer(this, 2, 0);
        rubber_right_fl.addBox(3.0F, -3.0F, 0.0F, 4, 6, 5, 0.0F);
        ModelRenderer rubber_outer_tl2_rr = new ModelRenderer(this, 5, 4);
        rubber_outer_tl2_rr.addBox(-6.0F, -5.0F, 0.0F, 1, 2, 5, 0.0F);
        ModelRenderer hub_left_rl = new ModelRenderer(this, 22, 7);
        hub_left_rl.addBox(-3.0F, -1.0F, 0.5F, 1, 2, 2, 0.0F);
        wheel_rr = new ModelRenderer(this, 22, 7);
        wheel_rr.setRotationPoint(23.0F, -7.0F, 21.0F);
        wheel_rr.addBox(-1.0F, -1.0F, 0.5F, 2, 2, 2, 0.0F);
        setRotateAngle(wheel_rr, 3.141592653589793F, 0.0F, 0.0F);
        ModelRenderer hub_left_fl = new ModelRenderer(this, 22, 7);
        hub_left_fl.addBox(-3.0F, -1.0F, 2.5F, 1, 2, 2, 0.0F);
        ModelRenderer hub_top_fl = new ModelRenderer(this, 22, 7);
        hub_top_fl.addBox(-1.0F, -3.0F, 2.5F, 2, 1, 2, 0.0F);
        container = new ModelRenderer(this, 0, 0);
        container.setRotationPoint(0.0F, 24.0F, 0.0F);
        container.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0, 0.0F);
        setRotateAngle(container, 0.0F, -1.5707963267948966F, 0.0F);
        ModelRenderer rubber_inner_tl_fl = new ModelRenderer(this, 5, 5);
        rubber_inner_tl_fl.addBox(-3.0F, -3.0F, 0.0F, 1, 1, 5, 0.0F);
        ModelRenderer rubber_outer_tr1_rr = new ModelRenderer(this, 4, 3);
        rubber_outer_tr1_rr.addBox(3.0F, -6.0F, 0.0F, 2, 3, 5, 0.0F);
        ModelRenderer seat_back_4 = new ModelRenderer(this, 5, 0);
        seat_back_4.addBox(4.0F, -6.1F, 5.0F, 1, 6, 5, 0.0F);
        setRotateAngle(seat_back_4, 0.0F, 0.0F, 0.20943951023931953F);
        ModelRenderer rubber_outer_tr2_rl = new ModelRenderer(this, 5, 4);
        rubber_outer_tr2_rl.addBox(5.0F, -5.0F, 0.0F, 1, 2, 5, 0.0F);
        ModelRenderer center_white_fl = new ModelRenderer(this, 22, 0);
        center_white_fl.setRotationPoint(0.0F, 0.0F, 1.0F);
        center_white_fl.addBox(-3.0F, -3.0F, 2.0F, 6, 6, 1, 0.0F);
        ModelRenderer rubber_inner_br_rr = new ModelRenderer(this, 5, 5);
        rubber_inner_br_rr.addBox(2.0F, 2.0F, 0.0F, 1, 1, 5, 0.0F);
        ModelRenderer body_1 = new ModelRenderer(this, 0, 17);
        body_1.addBox(-32.0F, 0.0F, -13.0F, 16, 2, 13, 0.0F);
        ModelRenderer rubber_outer_tl2_rl = new ModelRenderer(this, 5, 4);
        rubber_outer_tl2_rl.addBox(-6.0F, -5.0F, 0.0F, 1, 2, 5, 0.0F);
        ModelRenderer rubber_outer_tl1_rl = new ModelRenderer(this, 4, 3);
        rubber_outer_tl1_rl.addBox(-5.0F, -6.0F, 0.0F, 2, 3, 5, 0.0F);
        ModelRenderer rubber_outer_bl1_rl = new ModelRenderer(this, 4, 3);
        rubber_outer_bl1_rl.addBox(-5.0F, 3.0F, 0.0F, 2, 3, 5, 0.0F);
        ModelRenderer seat_bottom_3 = new ModelRenderer(this, 1, 5);
        seat_bottom_3.addBox(-5.0F, 0.0F, 0.0F, 5, 1, 5, 0.0F);
        seat_container = new ModelRenderer(this, 0, 0);
        seat_container.setRotationPoint(0.0F, -9.0F, 0.0F);
        seat_container.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0, 0.0F);
        ModelRenderer rubber_top_rl = new ModelRenderer(this, 0, 2);
        rubber_top_rl.addBox(-3.0F, -7.0F, 0.0F, 6, 4, 5, 0.0F);
        ModelRenderer rubber_left_fl = new ModelRenderer(this, 2, 0);
        rubber_left_fl.addBox(-7.0F, -3.0F, 0.0F, 4, 6, 5, 0.0F);
        ModelRenderer hub_tr_rl = new ModelRenderer(this, 22, 7);
        hub_tr_rl.addBox(1.0F, -2.0F, 0.5F, 1, 1, 2, 0.0F);
        ModelRenderer rubber_left_rr = new ModelRenderer(this, 2, 0);
        rubber_left_rr.addBox(-7.0F, -3.0F, 0.0F, 4, 6, 5, 0.0F);
        ModelRenderer hub_top_fr = new ModelRenderer(this, 22, 7);
        hub_top_fr.addBox(-1.0F, -3.0F, 2.5F, 2, 1, 2, 0.0F);
        ModelRenderer hub_right_fr = new ModelRenderer(this, 22, 7);
        hub_right_fr.addBox(2.0F, -1.0F, 2.5F, 1, 2, 2, 0.0F);
        ModelRenderer rubber_bottom_rl = new ModelRenderer(this, 0, 2);
        rubber_bottom_rl.addBox(-3.0F, 3.0F, 0.0F, 6, 4, 5, 0.0F);
        ModelRenderer seat_back = new ModelRenderer(this, 0, 0);
        seat_back.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0, 0.0F);
        ModelRenderer hub_tl_rr = new ModelRenderer(this, 22, 7);
        hub_tl_rr.addBox(-2.0F, -2.0F, 0.5F, 1, 1, 2, 0.0F);
        ModelRenderer hub_tl_fr = new ModelRenderer(this, 22, 7);
        hub_tl_fr.addBox(-2.0F, -2.0F, 2.5F, 1, 1, 2, 0.0F);
        ModelRenderer rubber_top_rr = new ModelRenderer(this, 0, 2);
        rubber_top_rr.addBox(-3.0F, -7.0F, 0.0F, 6, 4, 5, 0.0F);
        ModelRenderer rubber_inner_tr_rr = new ModelRenderer(this, 5, 5);
        rubber_inner_tr_rr.addBox(2.0F, -3.0F, 0.0F, 1, 1, 5, 0.0F);
        wheel_fr = new ModelRenderer(this, 22, 7);
        wheel_fr.setRotationPoint(-23.0F, -7.0F, 16.0F);
        wheel_fr.addBox(-1.0F, -1.0F, 2.5F, 2, 2, 2, 0.0F);
        ModelRenderer hub_tl_rl = new ModelRenderer(this, 22, 7);
        hub_tl_rl.addBox(-2.0F, -2.0F, 0.5F, 1, 1, 2, 0.0F);
        ModelRenderer rubber_outer_tr1_fr = new ModelRenderer(this, 4, 3);
        rubber_outer_tr1_fr.addBox(3.0F, -6.0F, 0.0F, 2, 3, 5, 0.0F);
        ModelRenderer seat_bottom_12 = new ModelRenderer(this, 1, 5);
        seat_bottom_12.addBox(-10.0F, 0.0F, -10.0F, 5, 1, 5, 0.0F);
        ModelRenderer hub_left_rr = new ModelRenderer(this, 22, 7);
        hub_left_rr.addBox(-3.0F, -1.0F, 0.5F, 1, 2, 2, 0.0F);
        ModelRenderer rubber_outer_bl1_rr = new ModelRenderer(this, 4, 3);
        rubber_outer_bl1_rr.addBox(-5.0F, 3.0F, 0.0F, 2, 3, 5, 0.0F);
        ModelRenderer hub_bl_fl = new ModelRenderer(this, 22, 7);
        hub_bl_fl.addBox(-2.0F, 1.0F, 2.5F, 1, 1, 2, 0.0F);
        ModelRenderer rubber_outer_bl2_rl = new ModelRenderer(this, 5, 4);
        rubber_outer_bl2_rl.addBox(-6.0F, 3.0F, 0.0F, 1, 2, 5, 0.0F);
        ModelRenderer hub_tl_fl = new ModelRenderer(this, 22, 7);
        hub_tl_fl.addBox(-2.0F, -2.0F, 2.5F, 1, 1, 2, 0.0F);
        ModelRenderer hub_left_fr = new ModelRenderer(this, 22, 7);
        hub_left_fr.addBox(-3.0F, -1.0F, 2.5F, 1, 2, 2, 0.0F);
        ModelRenderer seat_bottom_7 = new ModelRenderer(this, 1, 5);
        seat_bottom_7.addBox(0.0F, 0.0F, -10.0F, 5, 1, 5, 0.0F);
        ModelRenderer rubber_outer_tl2_fl = new ModelRenderer(this, 5, 4);
        rubber_outer_tl2_fl.addBox(-6.0F, -5.0F, 0.0F, 1, 2, 5, 0.0F);
        ModelRenderer rubber_outer_tr1_fl = new ModelRenderer(this, 4, 3);
        rubber_outer_tr1_fl.addBox(3.0F, -6.0F, 0.0F, 2, 3, 5, 0.0F);
        ModelRenderer rubber_inner_br_fl = new ModelRenderer(this, 5, 5);
        rubber_inner_br_fl.addBox(2.0F, 2.0F, 0.0F, 1, 1, 5, 0.0F);
        ModelRenderer seat_back_7 = new ModelRenderer(this, 5, 0);
        seat_back_7.addBox(4.0F, -12.1F, -10.0F, 1, 6, 5, 0.0F);
        setRotateAngle(seat_back_7, 0.0F, 0.0F, 0.20943951023931953F);
        ModelRenderer body_7 = new ModelRenderer(this, 0, 17);
        body_7.addBox(16.0F, 0.0F, -13.0F, 16, 2, 13, 0.0F);
        ModelRenderer body_wing_rl = new ModelRenderer(this, 8, 24);
        body_wing_rl.addBox(0.0F, 0.0F, -19.0F, 15, 2, 6, 0.0F);
        ModelRenderer rubber_outer_tl1_rr = new ModelRenderer(this, 4, 3);
        rubber_outer_tl1_rr.addBox(-5.0F, -6.0F, 0.0F, 2, 3, 5, 0.0F);
        ModelRenderer hub_right_fl = new ModelRenderer(this, 22, 7);
        hub_right_fl.addBox(2.0F, -1.0F, 2.5F, 1, 2, 2, 0.0F);
        ModelRenderer hub_bottom_rr = new ModelRenderer(this, 22, 7);
        hub_bottom_rr.addBox(-1.0F, 2.0F, 0.5F, 2, 1, 2, 0.0F);
        ModelRenderer seat_back_6 = new ModelRenderer(this, 5, 0);
        seat_back_6.addBox(4.0F, -12.1F, -5.0F, 1, 6, 5, 0.0F);
        setRotateAngle(seat_back_6, 0.0F, 0.0F, 0.20943951023931953F);
        ModelRenderer rubber_right_rr = new ModelRenderer(this, 2, 0);
        rubber_right_rr.addBox(3.0F, -3.0F, 0.0F, 4, 6, 5, 0.0F);
        ModelRenderer center_white_fr = new ModelRenderer(this, 22, 0);
        center_white_fr.setRotationPoint(0.0F, 0.0F, 1.0F);
        center_white_fr.addBox(-3.0F, -3.0F, 2.0F, 6, 6, 1, 0.0F);
        ModelRenderer seat_bottom_6 = new ModelRenderer(this, 1, 5);
        seat_bottom_6.addBox(-5.0F, 0.0F, 5.0F, 5, 1, 5, 0.0F);
        ModelRenderer rubber_bottom_fr = new ModelRenderer(this, 0, 2);
        rubber_bottom_fr.addBox(-3.0F, 3.0F, 0.0F, 6, 4, 5, 0.0F);
        ModelRenderer rubber_outer_tr2_rr = new ModelRenderer(this, 5, 4);
        rubber_outer_tr2_rr.addBox(5.0F, -5.0F, 0.0F, 1, 2, 5, 0.0F);
        ModelRenderer hub_bottom_rl = new ModelRenderer(this, 22, 7);
        hub_bottom_rl.addBox(-1.0F, 2.0F, 0.5F, 2, 1, 2, 0.0F);
        ModelRenderer seat_bottom_9 = new ModelRenderer(this, 1, 5);
        seat_bottom_9.addBox(-10.0F, 0.0F, 5.0F, 5, 1, 5, 0.0F);
        ModelRenderer body_wing_fl = new ModelRenderer(this, 8, 24);
        body_wing_fl.addBox(-15.0F, 0.0F, -19.0F, 15, 2, 6, 0.0F);
        ModelRenderer rubber_outer_br1_fl = new ModelRenderer(this, 4, 3);
        rubber_outer_br1_fl.addBox(3.0F, 3.0F, 0.0F, 2, 3, 5, 0.0F);
        ModelRenderer rubber_outer_tr2_fr = new ModelRenderer(this, 5, 4);
        rubber_outer_tr2_fr.addBox(5.0F, -5.0F, 0.0F, 1, 2, 5, 0.0F);
        ModelRenderer seat_bottom_2 = new ModelRenderer(this, 1, 5);
        seat_bottom_2.addBox(0.0F, 0.0F, -5.0F, 5, 1, 5, 0.0F);
        ModelRenderer body_6 = new ModelRenderer(this, 0, 17);
        body_6.addBox(0.0F, 0.0F, 0.0F, 16, 2, 13, 0.0F);
        ModelRenderer seat_back_3 = new ModelRenderer(this, 5, 0);
        seat_back_3.addBox(4.0F, -6.1F, -10.0F, 1, 6, 5, 0.0F);
        setRotateAngle(seat_back_3, 0.0F, 0.0F, 0.20943951023931953F);
        ModelRenderer rubber_inner_tr_fr = new ModelRenderer(this, 5, 5);
        rubber_inner_tr_fr.addBox(2.0F, -3.0F, 0.0F, 1, 1, 5, 0.0F);
        ModelRenderer hub_bl_rl = new ModelRenderer(this, 22, 7);
        hub_bl_rl.addBox(-2.0F, 1.0F, 0.5F, 1, 1, 2, 0.0F);
        ModelRenderer rubber_outer_bl2_rr = new ModelRenderer(this, 5, 4);
        rubber_outer_bl2_rr.addBox(-6.0F, 3.0F, 0.0F, 1, 2, 5, 0.0F);
        ModelRenderer rubber_outer_br1_fr = new ModelRenderer(this, 4, 3);
        rubber_outer_br1_fr.addBox(3.0F, 3.0F, 0.0F, 2, 3, 5, 0.0F);
        ModelRenderer hub_tr_fl = new ModelRenderer(this, 22, 7);
        hub_tr_fl.addBox(1.0F, -2.0F, 2.5F, 1, 1, 2, 0.0F);
        ModelRenderer hub_top_rl = new ModelRenderer(this, 22, 7);
        hub_top_rl.addBox(-1.0F, -3.0F, 0.5F, 2, 1, 2, 0.0F);
        ModelRenderer hub_right_rl = new ModelRenderer(this, 22, 7);
        hub_right_rl.addBox(2.0F, -1.0F, 0.5F, 1, 2, 2, 0.0F);
        ModelRenderer rubber_outer_tr1_rl = new ModelRenderer(this, 4, 3);
        rubber_outer_tr1_rl.addBox(3.0F, -6.0F, 0.0F, 2, 3, 5, 0.0F);
        ModelRenderer rubber_inner_bl_fr = new ModelRenderer(this, 5, 5);
        rubber_inner_bl_fr.addBox(-3.0F, 2.0F, 0.0F, 1, 1, 5, 0.0F);
        ModelRenderer rubber_left_rl = new ModelRenderer(this, 2, 0);
        rubber_left_rl.addBox(-7.0F, -3.0F, 0.0F, 4, 6, 5, 0.0F);
        ModelRenderer rubber_inner_tl_rl = new ModelRenderer(this, 5, 5);
        rubber_inner_tl_rl.addBox(-3.0F, -3.0F, 0.0F, 1, 1, 5, 0.0F);
        ModelRenderer rubber_bottom_fl = new ModelRenderer(this, 0, 2);
        rubber_bottom_fl.addBox(-3.0F, 3.0F, 0.0F, 6, 4, 5, 0.0F);
        ModelRenderer hub_br_fr = new ModelRenderer(this, 22, 7);
        hub_br_fr.addBox(1.0F, 1.0F, 2.5F, 1, 1, 2, 0.0F);
        ModelRenderer hub_right_rr = new ModelRenderer(this, 22, 7);
        hub_right_rr.addBox(2.0F, -1.0F, 0.5F, 1, 2, 2, 0.0F);
        ModelRenderer seat_back_1 = new ModelRenderer(this, 5, 0);
        seat_back_1.addBox(4.0F, -6.1F, 0.0F, 1, 6, 5, 0.0F);
        setRotateAngle(seat_back_1, 0.0F, 0.0F, 0.20943951023931953F);
        ModelRenderer seat_back_5 = new ModelRenderer(this, 5, 0);
        seat_back_5.addBox(4.0F, -12.1F, 0.0F, 1, 6, 5, 0.0F);
        setRotateAngle(seat_back_5, 0.0F, 0.0F, 0.20943951023931953F);
        ModelRenderer rubber_outer_br2_fr = new ModelRenderer(this, 5, 4);
        rubber_outer_br2_fr.addBox(5.0F, 3.0F, 0.0F, 1, 2, 5, 0.0F);
        ModelRenderer hub_br_rr = new ModelRenderer(this, 22, 7);
        hub_br_rr.addBox(1.0F, 1.0F, 0.5F, 1, 1, 2, 0.0F);
        ModelRenderer rubber_top_fr = new ModelRenderer(this, 0, 2);
        rubber_top_fr.addBox(-3.0F, -7.0F, 0.0F, 6, 4, 5, 0.0F);
        ModelRenderer rubber_right_fr = new ModelRenderer(this, 2, 0);
        rubber_right_fr.addBox(3.0F, -3.0F, 0.0F, 4, 6, 5, 0.0F);
        ModelRenderer rubber_inner_br_rl = new ModelRenderer(this, 5, 5);
        rubber_inner_br_rl.addBox(2.0F, 2.0F, 0.0F, 1, 1, 5, 0.0F);
        ModelRenderer center_white_rr = new ModelRenderer(this, 22, 0);
        center_white_rr.setRotationPoint(0.0F, 0.0F, 1.0F);
        center_white_rr.addBox(-3.0F, -3.0F, 0.0F, 6, 6, 1, 0.0F);
        ModelRenderer rubber_outer_br1_rl = new ModelRenderer(this, 4, 3);
        rubber_outer_br1_rl.addBox(3.0F, 3.0F, 0.0F, 2, 3, 5, 0.0F);
        ModelRenderer rubber_inner_tr_rl = new ModelRenderer(this, 5, 5);
        rubber_inner_tr_rl.addBox(2.0F, -3.0F, 0.0F, 1, 1, 5, 0.0F);
        ModelRenderer body_wing_fr = new ModelRenderer(this, 8, 24);
        body_wing_fr.addBox(-15.0F, 0.0F, 13.0F, 15, 2, 6, 0.0F);
        ModelRenderer rubber_outer_bl1_fl = new ModelRenderer(this, 4, 3);
        rubber_outer_bl1_fl.addBox(-5.0F, 3.0F, 0.0F, 2, 3, 5, 0.0F);
        ModelRenderer rubber_inner_br_fr = new ModelRenderer(this, 5, 5);
        rubber_inner_br_fr.addBox(2.0F, 2.0F, 0.0F, 1, 1, 5, 0.0F);
        ModelRenderer rubber_inner_tl_rr = new ModelRenderer(this, 5, 5);
        rubber_inner_tl_rr.addBox(-3.0F, -3.0F, 0.0F, 1, 1, 5, 0.0F);
        ModelRenderer rubber_outer_br2_rl = new ModelRenderer(this, 5, 4);
        rubber_outer_br2_rl.addBox(5.0F, 3.0F, 0.0F, 1, 2, 5, 0.0F);
        ModelRenderer hub_top_rr = new ModelRenderer(this, 22, 7);
        hub_top_rr.addBox(-1.0F, -3.0F, 0.5F, 2, 1, 2, 0.0F);
        ModelRenderer hub_tr_fr = new ModelRenderer(this, 22, 7);
        hub_tr_fr.addBox(1.0F, -2.0F, 2.5F, 1, 1, 2, 0.0F);
        ModelRenderer seat_bottom_8 = new ModelRenderer(this, 1, 5);
        seat_bottom_8.addBox(-5.0F, 0.0F, -10.0F, 5, 1, 5, 0.0F);
        ModelRenderer seat_back_2 = new ModelRenderer(this, 5, 0);
        seat_back_2.addBox(4.0F, -6.1F, -5.0F, 1, 6, 5, 0.0F);
        setRotateAngle(seat_back_2, 0.0F, 0.0F, 0.20943951023931953F);
        ModelRenderer hub_br_rl = new ModelRenderer(this, 22, 7);
        hub_br_rl.addBox(1.0F, 1.0F, 0.5F, 1, 1, 2, 0.0F);
        ModelRenderer rubber_outer_tl1_fl = new ModelRenderer(this, 4, 3);
        rubber_outer_tl1_fl.addBox(-5.0F, -6.0F, 0.0F, 2, 3, 5, 0.0F);
        ModelRenderer seat_back_8 = new ModelRenderer(this, 5, 0);
        seat_back_8.addBox(4.0F, -12.1F, 5.0F, 1, 6, 5, 0.0F);
        setRotateAngle(seat_back_8, 0.0F, 0.0F, 0.20943951023931953F);
        ModelRenderer rubber_outer_tr2_fl = new ModelRenderer(this, 5, 4);
        rubber_outer_tr2_fl.addBox(5.0F, -5.0F, 0.0F, 1, 2, 5, 0.0F);
        ModelRenderer rubber_outer_br1_rr = new ModelRenderer(this, 4, 3);
        rubber_outer_br1_rr.addBox(3.0F, 3.0F, 0.0F, 2, 3, 5, 0.0F);
        ModelRenderer rubber_outer_tl2_fr = new ModelRenderer(this, 5, 4);
        rubber_outer_tl2_fr.addBox(-6.0F, -5.0F, 0.0F, 1, 2, 5, 0.0F);
        ModelRenderer center_white_rl = new ModelRenderer(this, 22, 0);
        center_white_rl.setRotationPoint(0.0F, 0.0F, 1.0F);
        center_white_rl.addBox(-3.0F, -3.0F, 0.0F, 6, 6, 1, 0.0F);
        ModelRenderer rubber_inner_bl_rr = new ModelRenderer(this, 5, 5);
        rubber_inner_bl_rr.addBox(-3.0F, 2.0F, 0.0F, 1, 1, 5, 0.0F);
        ModelRenderer rubber_inner_bl_rl = new ModelRenderer(this, 5, 5);
        rubber_inner_bl_rl.addBox(-3.0F, 2.0F, 0.0F, 1, 1, 5, 0.0F);
        ModelRenderer rubber_left_fr = new ModelRenderer(this, 2, 0);
        rubber_left_fr.addBox(-7.0F, -3.0F, 0.0F, 4, 6, 5, 0.0F);
        wheel_rl = new ModelRenderer(this, 22, 7);
        wheel_rl.setRotationPoint(23.0F, -7.0F, -21.0F);
        wheel_rl.addBox(-1.0F, -1.0F, 0.5F, 2, 2, 2, 0.0F);
        ModelRenderer body_wing_rr = new ModelRenderer(this, 8, 24);
        body_wing_rr.addBox(0.0F, 0.0F, 13.0F, 15, 2, 6, 0.0F);
        ModelRenderer hub_br_fl = new ModelRenderer(this, 22, 7);
        hub_br_fl.addBox(1.0F, 1.0F, 2.5F, 1, 1, 2, 0.0F);
        ModelRenderer body_8 = new ModelRenderer(this, 0, 17);
        body_8.addBox(16.0F, 0.0F, 0.0F, 16, 2, 13, 0.0F);
        ModelRenderer rubber_inner_tl_fr = new ModelRenderer(this, 5, 5);
        rubber_inner_tl_fr.addBox(-3.0F, -3.0F, 0.0F, 1, 1, 5, 0.0F);
        ModelRenderer body_5 = new ModelRenderer(this, 0, 17);
        body_5.addBox(0.0F, 0.0F, -13.0F, 16, 2, 13, 0.0F);
        ModelRenderer rubber_outer_bl1_fr = new ModelRenderer(this, 4, 3);
        rubber_outer_bl1_fr.addBox(-5.0F, 3.0F, 0.0F, 2, 3, 5, 0.0F);
        ModelRenderer hub_bl_rr = new ModelRenderer(this, 22, 7);
        hub_bl_rr.addBox(-2.0F, 1.0F, 0.5F, 1, 1, 2, 0.0F);
        ModelRenderer rubber_bottom_rr = new ModelRenderer(this, 0, 2);
        rubber_bottom_rr.addBox(-3.0F, 3.0F, 0.0F, 6, 4, 5, 0.0F);
        ModelRenderer hub_bottom_fr = new ModelRenderer(this, 22, 7);
        hub_bottom_fr.addBox(-1.0F, 2.0F, 2.5F, 2, 1, 2, 0.0F);
        ModelRenderer seat_bottom_10 = new ModelRenderer(this, 1, 5);
        seat_bottom_10.addBox(-10.0F, 0.0F, 0.0F, 5, 1, 5, 0.0F);
        ModelRenderer rubber_outer_bl2_fl = new ModelRenderer(this, 5, 4);
        rubber_outer_bl2_fl.addBox(-6.0F, 3.0F, 0.0F, 1, 2, 5, 0.0F);
        ModelRenderer body_3 = new ModelRenderer(this, 0, 17);
        body_3.addBox(-16.0F, 0.0F, -13.0F, 16, 2, 13, 0.0F);
        wheel_fl = new ModelRenderer(this, 22, 7);
        wheel_fl.setRotationPoint(-23.0F, -7.0F, -16.0F);
        wheel_fl.addBox(-1.0F, -1.0F, 2.5F, 2, 2, 2, 0.0F);
        setRotateAngle(wheel_fl, 0.0F, 3.141592653589793F, 0.0F);
        wheel_rl.addChild(rubber_right_rl);
        container.addChild(body_container);
        wheel_rr.addChild(rubber_outer_br2_rr);
        seat_container.addChild(seat_bottom_5);
        wheel_fl.addChild(hub_bottom_fl);
        wheel_fr.addChild(hub_bl_fr);
        seat_container.addChild(seat_bottom_1);
        wheel_fl.addChild(rubber_outer_br2_fl);
        wheel_fr.addChild(rubber_outer_tl1_fr);
        wheel_fl.addChild(rubber_inner_bl_fl);
        body_container.addChild(body_4);
        wheel_fl.addChild(rubber_inner_tr_fl);
        seat_container.addChild(seat_bottom_4);
        wheel_rr.addChild(hub_tr_rr);
        body_container.addChild(body_2);
        seat_container.addChild(seat_bottom_11);
        wheel_fr.addChild(rubber_outer_bl2_fr);
        wheel_fl.addChild(rubber_top_fl);
        wheel_fl.addChild(rubber_right_fl);
        wheel_rr.addChild(rubber_outer_tl2_rr);
        wheel_rl.addChild(hub_left_rl);
        container.addChild(wheel_rr);
        wheel_fl.addChild(hub_left_fl);
        wheel_fl.addChild(hub_top_fl);
        wheel_fl.addChild(rubber_inner_tl_fl);
        wheel_rr.addChild(rubber_outer_tr1_rr);
        seat_back.addChild(seat_back_4);
        wheel_rl.addChild(rubber_outer_tr2_rl);
        wheel_fl.addChild(center_white_fl);
        wheel_rr.addChild(rubber_inner_br_rr);
        body_container.addChild(body_1);
        wheel_rl.addChild(rubber_outer_tl2_rl);
        wheel_rl.addChild(rubber_outer_tl1_rl);
        wheel_rl.addChild(rubber_outer_bl1_rl);
        seat_container.addChild(seat_bottom_3);
        container.addChild(seat_container);
        wheel_rl.addChild(rubber_top_rl);
        wheel_fl.addChild(rubber_left_fl);
        wheel_rl.addChild(hub_tr_rl);
        wheel_rr.addChild(rubber_left_rr);
        wheel_fr.addChild(hub_top_fr);
        wheel_fr.addChild(hub_right_fr);
        wheel_rl.addChild(rubber_bottom_rl);
        seat_container.addChild(seat_back);
        wheel_rr.addChild(hub_tl_rr);
        wheel_fr.addChild(hub_tl_fr);
        wheel_rr.addChild(rubber_top_rr);
        wheel_rr.addChild(rubber_inner_tr_rr);
        container.addChild(wheel_fr);
        wheel_rl.addChild(hub_tl_rl);
        wheel_fr.addChild(rubber_outer_tr1_fr);
        seat_container.addChild(seat_bottom_12);
        wheel_rr.addChild(hub_left_rr);
        wheel_rr.addChild(rubber_outer_bl1_rr);
        wheel_fl.addChild(hub_bl_fl);
        wheel_rl.addChild(rubber_outer_bl2_rl);
        wheel_fl.addChild(hub_tl_fl);
        wheel_fr.addChild(hub_left_fr);
        seat_container.addChild(seat_bottom_7);
        wheel_fl.addChild(rubber_outer_tl2_fl);
        wheel_fl.addChild(rubber_outer_tr1_fl);
        wheel_fl.addChild(rubber_inner_br_fl);
        seat_back.addChild(seat_back_7);
        body_container.addChild(body_7);
        body_container.addChild(body_wing_rl);
        wheel_rr.addChild(rubber_outer_tl1_rr);
        wheel_fl.addChild(hub_right_fl);
        wheel_rr.addChild(hub_bottom_rr);
        seat_back.addChild(seat_back_6);
        wheel_rr.addChild(rubber_right_rr);
        wheel_fr.addChild(center_white_fr);
        seat_container.addChild(seat_bottom_6);
        wheel_fr.addChild(rubber_bottom_fr);
        wheel_rr.addChild(rubber_outer_tr2_rr);
        wheel_rl.addChild(hub_bottom_rl);
        seat_container.addChild(seat_bottom_9);
        body_container.addChild(body_wing_fl);
        wheel_fl.addChild(rubber_outer_br1_fl);
        wheel_fr.addChild(rubber_outer_tr2_fr);
        seat_container.addChild(seat_bottom_2);
        body_container.addChild(body_6);
        seat_back.addChild(seat_back_3);
        wheel_fr.addChild(rubber_inner_tr_fr);
        wheel_rl.addChild(hub_bl_rl);
        wheel_rr.addChild(rubber_outer_bl2_rr);
        wheel_fr.addChild(rubber_outer_br1_fr);
        wheel_fl.addChild(hub_tr_fl);
        wheel_rl.addChild(hub_top_rl);
        wheel_rl.addChild(hub_right_rl);
        wheel_rl.addChild(rubber_outer_tr1_rl);
        wheel_fr.addChild(rubber_inner_bl_fr);
        wheel_rl.addChild(rubber_left_rl);
        wheel_rl.addChild(rubber_inner_tl_rl);
        wheel_fl.addChild(rubber_bottom_fl);
        wheel_fr.addChild(hub_br_fr);
        wheel_rr.addChild(hub_right_rr);
        seat_back.addChild(seat_back_1);
        seat_back.addChild(seat_back_5);
        wheel_fr.addChild(rubber_outer_br2_fr);
        wheel_rr.addChild(hub_br_rr);
        wheel_fr.addChild(rubber_top_fr);
        wheel_fr.addChild(rubber_right_fr);
        wheel_rl.addChild(rubber_inner_br_rl);
        wheel_rr.addChild(center_white_rr);
        wheel_rl.addChild(rubber_outer_br1_rl);
        wheel_rl.addChild(rubber_inner_tr_rl);
        body_container.addChild(body_wing_fr);
        wheel_fl.addChild(rubber_outer_bl1_fl);
        wheel_fr.addChild(rubber_inner_br_fr);
        wheel_rr.addChild(rubber_inner_tl_rr);
        wheel_rl.addChild(rubber_outer_br2_rl);
        wheel_rr.addChild(hub_top_rr);
        wheel_fr.addChild(hub_tr_fr);
        seat_container.addChild(seat_bottom_8);
        seat_back.addChild(seat_back_2);
        wheel_rl.addChild(hub_br_rl);
        wheel_fl.addChild(rubber_outer_tl1_fl);
        seat_back.addChild(seat_back_8);
        wheel_fl.addChild(rubber_outer_tr2_fl);
        wheel_rr.addChild(rubber_outer_br1_rr);
        wheel_fr.addChild(rubber_outer_tl2_fr);
        wheel_rl.addChild(center_white_rl);
        wheel_rr.addChild(rubber_inner_bl_rr);
        wheel_rl.addChild(rubber_inner_bl_rl);
        wheel_fr.addChild(rubber_left_fr);
        container.addChild(wheel_rl);
        body_container.addChild(body_wing_rr);
        wheel_fl.addChild(hub_br_fl);
        body_container.addChild(body_8);
        wheel_fr.addChild(rubber_inner_tl_fr);
        body_container.addChild(body_5);
        wheel_fr.addChild(rubber_outer_bl1_fr);
        wheel_rr.addChild(hub_bl_rr);
        wheel_rr.addChild(rubber_bottom_rr);
        wheel_fr.addChild(hub_bottom_fr);
        seat_container.addChild(seat_bottom_10);
        wheel_fl.addChild(rubber_outer_bl2_fl);
        body_container.addChild(body_3);
        container.addChild(wheel_fl);
    }

    @Override
    public void render(Entity entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scale) {
        EntityVehicle vehicle = (EntityVehicle) entity;

        if (vehicle.isInputLeftDown() == vehicle.isInputRightDown()) {
            // none, or both
            wheel_fl.rotateAngleY = 3.14159F;
            wheel_fr.rotateAngleY = 0.0F;
        } else if (vehicle.isInputRightDown()) {
            // right only
            wheel_fl.rotateAngleY = 3.52557F;
            wheel_fr.rotateAngleY = 0.383972F;
        } else {
            // left only
            wheel_fl.rotateAngleY = 2.75762F;
            wheel_fr.rotateAngleY = -0.383972F;
        }

        GlStateManager.pushMatrix();
        GlStateManager.translate(container.offsetX, container.offsetY, container.offsetZ);
        GlStateManager.translate(container.rotationPointX * scale, container.rotationPointY * scale, container.rotationPointZ * scale);
        GlStateManager.scale(0.5D, 0.5D, 0.5D);
        GlStateManager.translate(-container.offsetX, -container.offsetY, -container.offsetZ);
        GlStateManager.translate(-container.rotationPointX * scale, -container.rotationPointY * scale, -container.rotationPointZ * scale);
        container.render(scale);
        GlStateManager.popMatrix();
    }

    private void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }
}
